### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by smotched** [webstudio-is/webstudio-designer#17]
@kof could you write a little bit about the projects tech for contributors, including guide for local development and your vision for how all the parts of webstudio fit together including the webstudio-designer.

A roadmap with the **necessary** features, and **bonus** enhancements you think might be cool to have would be useful too. [an example](https://github.com/supabase/supabase/blob/master/DEVELOPERS.md)

**Comment by kof** [comment]
Glad you asked! Will do asap

**Comment by kof** [comment]
Ok, I am on it now, what would you like to know regarding contributing?

**Comment by kof** [comment]
Ok, here is what I got so far, please do tell me specific things your are missing there

https://github.com/webstudio-is/webstudio/blob/main/docs/contributing.md

**Comment by kof** [comment]
Regarding a roadmap - we will flesh it out as we go, right now we are missing a lot of basic functionality, so I am happy to discuss what you and everyone else think is the most high priority feature to work on!

I am not creating roadmap yet, because I want it to emerge out of community, instead of telling the community what the roadmap is.

**Comment by kof** [comment]
Ok I created a board with the issues we have so far, let me know if it makes sense https://github.com/orgs/webstudio-is/projects/1/views/1

**Comment by kof** [comment]
Will close it for now, please reopen once you encounter missing things
