### ISSUE TITLE
Image component and src prop

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#196]
As a user I want to be able to drop an image component onto canvas then select src prop from asset manager

## Basics

- [x] create basic Image component for sdk
- [x] don't load image if its off screen (lazy prop by default, that's it?)
- [x] add srcset and sizes to image component
- [x] handle File type in props panel that lets you select image
- [x] define what we can do for high res screens and low res screens (srcset?)
- [x] we should be able to know what image sizes are needed in each depending on the breakpoint and/or layout to pass with the src to optimizer the right size

## Questions

- [ ] should user be able to put arbitrary URL instead of selecting an image from asset manager?

**Comment by kof** [comment]
Check out image component from astra https://docs.astro.build/en/guides/integrations-guide/image/

I don't know if we can even use it, if not - it can be a big inspiration

**Comment by istarkov** [comment]
Images:


# img vs picture tag on responsive resolutions.


# IMG


## 1. _img_ tag is well suited if on all breakpoints you have same width, heights for the image.

In that case all you need is single `srcset` with dpr set.

```html
<img 
  srcset="https://via.placeholder.com/128 1x, https://via.placeholder.com/256 2x" 
  src="https://via.placeholder.com/256" 
  width="120" height="120"
>
```

For devices with 

- `window.devicePixelRatio = 1` will be loaded `https://via.placeholder.com/128` 
- `>=2` will be loaded `https://via.placeholder.com/256`

There is no need to support dpi >= 2 because of physical limitations of oled screens

see explanation: https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/capping-image-fidelity-on-ultra-high-resolution-devices.html



## 2. img tag also is ok to use if aspect-ratio is +-fixed, i.e. like


```html
<img
  alt=""
  sizes="
    (max-width: 600px) 100vw, 
    (max-width: 1200px) 50vw, 
    30vw
  "
  srcset="
    https://via.placeholder.com/64     64w,
    https://via.placeholder.com/96     96w,
    https://via.placeholder.com/128   128w,
    https://via.placeholder.com/256   256w,
    https://via.placeholder.com/384   384w,
    https://via.placeholder.com/640   640w,
    https://via.placeholder.com/750   750w,
    https://via.placeholder.com/828   828w,
    https://via.placeholder.com/1080 1080w,
    https://via.placeholder.com/1200 1200w,
    https://via.placeholder.com/1920 1920w,
    https://via.placeholder.com/2048 2048w,
    https://via.placeholder.com/3840 3840w
  "
  src="https://via.placeholder.com/3840"
  decoding="async"
/>
```

So on smaller screens it assume that image width is equal to device width, 
on a medium it assume that image width is half size of device with,
and on big screen it assume that image width is 30% of device width.


It works like:

1. Find first suitable media in `sizes` take width i.e 100vw, 50vw, 30vw
2. Find in srcset nearest suitable 
(most browsers selects nearest larger, BUT for example if browser have image with larger resolution in cache it will use it (chrome), safari ios will not load higher resolution image on screen rotation)


`sizes` can be written in `px` like

```
(max-width: 600px) 100px, 
(max-width: 1200px) 50px, 
30px
```

BUT algorithm before finding suitable image will multiply px on devicePixelRatio and will try to find images,
usually that cause questions as it always loads not what you want.

Also why so huge srcset? Its example from nextjs and its autogenerate. 

The only optimizarion nextjs uses is to remove smallest impossible breakpoints
https://github.com/vercel/next.js/blob/canary/packages/next/client/image.tsx#L168

Otherwise nextjs needs to have full parser of media queries.


**PROS for img tag**

In case of fixed size gives the shortes possible and readable html.
In case of fixed aspect ratios it easy to think in terms like this Image on card will be 100vw on mobile,
50vw in all other cases.
Just single tag.

**CONS**

Nor 1 nor 2 will not work with in case if aspect ratio is different on some breakpoints
(see caching issue, safari issue, inability to use px (see devicePixelRatio), different algorithms to select nearest suitable image. 
If Editor UI will allow to select different aspect ratios on different breakpoint all above is not suitable.
No different image formats support i.e webp, avif etc.
In case of 2. would be hard to not load images with dpr>=2 (device-pixel-ratio css could help)



# PICTURE

Allows everything


```html
<picture><source
    media="screen and (min-width: 640px)"
    srcset="
      https://via.placeholder.com/640.webp 1x,
      https://via.placeholder.com/1280.webp 2x
    "
    type="image/webp" />
  <source
    srcset="
      https://via.placeholder.com/320.webp 1x,
      https://via.placeholder.com/640.webp 2x
    "
    type="image/webp" />
  <source
    media="screen and (min-width: 640px)"
    srcset="
    https://via.placeholder.com/640.jpg 1x,
    https://via.placeholder.com/1280.jpg 2x
    " />
  <source
    srcset="
    https://via.placeholder.com/320.jpg 1x,
    https://via.placeholder.com/640.jpg 2x
    " />
  <img
    class=""
    alt=""
    src="LOADED WHEN YOU DONT NEED TOO"
/></picture>
```


Allows to set media query and dpr for each media. More redable and predictable behaviour.
Allows to select different aspect ratios for every breakpoint.


**PROS**

Allows mostly everything, more human readable vs img. 
Supports different aspect ratios on different resolution.
Supports different image formats.


**CONS**

In a lot of frameworks and some browsers has issue that fallbeck img src is loaded independent of srcset. (Not shown but loaded)
Need to be omitted on server and be set on useEffect.

MUUCH more tags vs img (perf and size).

Sometimes issues with styling - what to style picture or img, or both. I sticked to style both.


**MY PS**

I checked huge code db from my company, we use different aspect-ratio in one case, 
hack to load 1x1px image on mobile instead of full image (something with <link rel preload> for hero image)

In all other cases aspect-rations are preserved.



Builder IO uses the best of 2th world. It uses picture tag to support non webp format as fallback.
And uses img + srcset and sizes for pictire source and image.


**IMO**


IMO Aspect Ratio should be fixed in UI for all breakpoints - this covers 99% use cases. The last 1% can be covered with display:none etc.

For images without width set in UI we need to calculate it on all breakpoints in vw units,
or use good predefined behaviour.

Good predfined behaviour for example is to define that every image has near 80-90vw width on mobile,
50vw on resolutions up to 2k pixels, 30vw on above.

**Comment by kof** [comment]
- We should also think of a better initial loading experience on weak networks. We have been thinking to render something really small but make it look nice and have image colors but use gradients to render it, basically a few bytes. Here is a discussion https://github.com/webstudio-is/webstudio-designer/issues/171. This is definitely after beta, but we should think what would be better for this too

- Holding layout in place before image is loaded - is picture better?

> IMO Aspect Ratio should be fixed in UI for all breakpoints - this covers 99% use cases. The last 1% can be covered with display:none etc.

You mean in the rare case of having a different aspect ratio, user would just use different images in different breakpoints and  hide the one that isn't needed, right? 

> For images without width set in UI we need to calculate it on all breakpoints in vw units,
or use good predefined behaviour.

I would expect images to not have a width set by the user most of the time, because its a lot of work especially for each breakpoint.

**Comment by kof** [comment]
We decided to go with <picture> but use srcset only for now, without using <source> ... we will render <picture> just for the future, to avoid adding it later when we need it.

**Comment by kof** [comment]
This is done, right?
