### ISSUE TITLE
Design for toast components

### ISSUE THREAD

**Issue by SaraVieira** [webstudio-is/webstudio-designer#210]
Right now we have toasts in the application but the deisgn is very basic and needs some tweaking as we can see here:

![image](https://user-images.githubusercontent.com/1051509/182119955-5ddcc916-2c50-46de-8c4d-21c1567a3d45.png)
![image](https://user-images.githubusercontent.com/1051509/182119981-d2c07874-45a8-4e10-b5d3-bf93d29cb82b.png)

An updated design would be better for the user

**Comment by taylornowotny** [comment]
Can you give me some examples of how and when these toasts are used in context?

**Comment by SaraVieira** [comment]
Sure!

A success can be something like: your site has been published after you click the publish button 

An error could be: your image is bigger than 10mb when uploading an image

**Comment by SaraVieira** [comment]
One thing i can think the normal one can be used is also tell new things in the platform and redirect people to a changelog

**Comment by kof** [comment]
I would say toasts is usually the last resort, when showing error/hint inline or in a tooltip is not an option, because there is no place to show.

E.g. something happened and there is no specific place to show an error, e.g. because error is generic or happened on a collaborative user's side once we have collaborative feature.

**Comment by taylornowotny** [comment]
Designs done and added to the design system
