### ISSUE TITLE
Share Dialog redesign

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#227]
One thing we realized that its not clear that the shared site is the current state of the development and it doesn't require publishing. It's always instantly awailable.

**Comment by taylornowotny** [comment]
That's a really cool feature and definitely something we want to make explicit, since it's counter intuitive. 

What are some other features that would be useful when sharing?

We should have a way to share the project so that when someone clicks the link, the site is opened in the Webstudio UI. Webflow does this and it's essential for getting someone else's help troubleshooting. There should be a way to share the non-editable site (read-only) and a way to share the whole site, including editing capabilities (clone). The latter would make a copy of the site in the Webstudio acct of the person who opened the link. There are some details to think through here but that's how Webflow does it and these features are heavily utilised. 

I like how Notion does sharing, although they have a lot more sharing options than we will be able to provide at beta.
(https://www.notion.so/help/sharing-and-permissions)

**Comment by kof** [comment]
Bit of info that we should be aware of: current url inside designer `/designer/{projectId}` is actually a sharable editable project URL, though its like giving someone full access to the site with no way to revoke that access. Long term we should not allow this and have a more granular control for editable sharable link.

**Comment by kof** [comment]
We have currently these urls we could explicitly show and explain in the share dialog:

1. Share current site in  design mode (same URL as the designer itself for now, but still can be explicitly stated)
2. Share current site in preview mode (what we have now in the share dialog), should explain that this is basically like a production, it will run everything, except that it's not published to the edge infrastructure.
3. Share a clonable site: https://alpha.webstudio.is/rest/project/clone/{domain} this will let you clone a site using the domain. So the user of that URL will have a copy of the site, not affecting the original build

**Comment by kof** [comment]
In addition we should think if we want to enable sharing a specific version of the build. We have the versions in the database (a new one is created when publishing).

It could a menu button or a select box that would allow you to change the version and that would change all the URLs in the share dialog to the specific version

**Comment by markxtang** [comment]
The Goal of our Share dialog is to be able to give access to the Webstudio file and maintain some control over user permissions. There are 3 levels of access we want to be available. 

1. User can see previews of the file
2. User can edit text within the file, but cannot change the design.
3. User has full access design and edit text.

We plan to give this control via link sharing. The MVP would be a single link with different sharing permissions ala Notion:
![image](https://user-images.githubusercontent.com/122043657/212751119-22929aaa-0b73-4cbb-8627-58df2eb5c62d.png)

We also want to have the ability to generate multiple links in order to give groups of users different permission levels. This is similar to Pitch.com:
![image](https://user-images.githubusercontent.com/122043657/212751360-a88d1767-e7b0-4a09-b3cc-3464df749146.png)

We need to create a UI that fulfills these requirements in a clear, concise and helpful manner.

**Comment by taylornowotny** [comment]
(deleted mark's comment becuase the screenshots had our actual links in them)

**Comment by taylornowotny** [comment]
Design is done and documented
