### ISSUE TITLE
Optimize published site bundle

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#238]
Currently its heavily bundling a lot of unnecessary code that is only used in design mode.

**Comment by TrySound** [comment]
Most of published code is react and remix. Though one chunk still has more code than we expected.

A few icons still appear in bundle. This means we need to split components and their meta. Ivan is working on this I think.

All components are appear in bundle. So I think the right way would be to statically compute all these components. Though overall I think this issue is solved.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/5635476/204834154-f5d2af27-8a2e-4f7f-bdd0-bdc2b20ad273.png">

**Comment by kof** [comment]
regarding icons, please create an issue with a proposal on how to provide icons from SDK components while keeping them out of the published site bundle
