### ISSUE TITLE
Breadcrumbs under the canvas

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#4]
We need to know when we select an instance on the canvas, where that instance is in the hierarchy

**Comment by smotched** [comment]
To the right of the breadcrumb they have a button to expand the breadcrumb into a tree, I think this is a good approach because if we anticipate overtime there will be deeply tested nodes. We can just add an overflow scroll to the sidebar for now but for things that nest like this it might make more sense to utilize the full width of the screen instead of a fixed 250px.

**Comment by kof** [comment]
Oh nice, I didn't notice it, it is well hidden! I think such tree needs to be on the right, we need that vertical space for the canvas

**Comment by kof** [comment]
https://user-images.githubusercontent.com/52824/159706308-0162966a-97c2-4b2d-bdc7-346e3cc14787.mp4

released

**Comment by smotched** [comment]
looks great @kof
