### ISSUE TITLE
Clean and refactor <Button> to make it in sync with Figma

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#450]
`<Button>` was originally copied from somewhere. It has variants that are not from our design system, and it doesn't have variants that we have in Figma.

- [x] Remove from `<Button>` everything that's not defined in Figma
- [x] Add variants from Figma
- [x] Add a `pending` variant (need it in the Pages UI) that:
   - adds "..." to the label (questionable as adding "..." is not the only change we wan't to make to the text, e.g. not "Create..." but "Creating...")
   - sets `cursor` to `wait`
   - sets `pointer-events: none`

**Comment by rpominov** [comment]
@taylornowotny I've noticed that the style of "create page" button is not one of our standard buttons here https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/Designer-UI?node-id=2787%3A51405&t=NNnewVTeHAqiHF2s-0

Should it be added there? 

Asking because I wonder how I should define it in code:
 - as a reusable variant of Button,
 - or as a special case used only in pages panel.

**Comment by taylornowotny** [comment]
I am actually revising the button components today. I will have an answer for you by tomorrow

**Comment by rpominov** [comment]
Hey @taylornowotny, are you still working on revising the button?

**Comment by taylornowotny** [comment]
Yes, sorry had to prioritize other things past few days

**Comment by taylornowotny** [comment]
https://user-images.githubusercontent.com/86495896/205133781-2a9ac3bd-961c-4303-9be6-366e06924e02.mov

new button component is done! We may add a secondary color variant later. Here's a demo of how the component works.

Pay special notice to the layers of this component. The text has 2px padding on left & right for example. This is because text needs a little more space around it than icons need, so you can swap out the text and icons of this component using the component properties and the visual spacing will always be balanced.

**Comment by rpominov** [comment]
@taylornowotny There's a problem with the `ghost` type button. It only works well with a light background:

<img width="183" alt="Screenshot 2023-01-12 at 15 51 53" src="https://user-images.githubusercontent.com/825702/212060245-484e95ea-e2c5-493e-a0fe-059c835e57bf.png">

But when background is dark, it looks like this:

<img width="179" alt="Screenshot 2023-01-12 at 15 52 39" src="https://user-images.githubusercontent.com/825702/212060319-73741254-6c62-4984-80eb-56c94da86753.png">

Not sure how to solve this. Maybe we need `ghost-light` and `ghost-dark` as separate types.

**Comment by kof** [comment]
We didn't work on dark mode properly yet at all

**Comment by taylornowotny** [comment]
This is totally ok. A designer will never put the button or any element in
a context where it doesn’t have enough contrast to be visible.  The ghost
button will certainly have white text in dark mode.

Since dark mode is not designed yet we should disable it until then. We can
design it at any time but we’re choosing to prioritize new features.
