### ISSUE TITLE
CSS input with values/units autocomplete and drag

### ISSUE THREAD

**Issue by natlusyht** [webstudio-is/webstudio-designer#52]
The following is the spec for the input component that should have the general features and be able to support the extensions where needed.

# General

Should be able to input any arbitrary value with features that make enhance the experience.

## unit detection

>see chrome dev tools as an example

should show a arrow icon when the mouse is over a unit.

<img width="85" alt="Screenshot 2022-05-26 at 2 03 23 PM" src="https://user-images.githubusercontent.com/105234327/170475940-22ff3930-f5ea-469a-80d8-bcd9d0b486b3.png">

## number detection

>see chrome dev tools as an example

should show a [ew-resize cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) when hovering over a number.

![3-resize](https://user-images.githubusercontent.com/105234327/170476464-86e1b927-db1e-4b69-aa72-8da7e67c8909.gif)

> for both of the above we can either
> 1. destructive implementation: spans/divs within a rich "input". (this is what chrome dev-tools uses)
> 2. non-destructive implementation: use `measureText`, `style.cusror` and `mousemove` on the native input element to detect and decorate the input without the need for a rich "input". essentially using mouse x-coordinates relative to the input detect whether the mouse is over a unit/number from the current value of the input and update `style.cursor` based on that.

## Auto completion

should autocomplete valid property values as specified for that instance of the input.

<img width="241" alt="Screenshot 2022-05-26 at 2 27 34 PM" src="https://user-images.githubusercontent.com/105234327/170479254-a64e8d23-92e0-4c6e-a339-c9d392bcb897.png">

# Extensions

Should be able to support the following add-ons depending on the input instance

## ~~Auto-correct/delimited values~~

<details>
<summary>Archived</summary>
Should be able to add support for multiple delimited values and masked values such that i.e `10px10px` is `10px 10px` and `10px, 10px` is `10px 10px` essentially should be able to detect correct almost valid values to their valid counterparts and mask any denylisted characters to their counter parts i.e `comma` to `space` if specified.

an example of masking [imask.js.org](https://imask.js.org)

<img width="438" alt="Screenshot 2022-05-26 at 2 21 24 PM" src="https://user-images.githubusercontent.com/105234327/170478415-71c620ef-2c9f-4cf2-9cba-d4f706a1e6b2.png">
</details>

## ~~Expansion control~~

<details>
<summary>Archived</summary>
Should be able to add a control that based on the delimiter(could be space or comma) can add a value to the input, examples including:

<img width="139" alt="Screenshot 2022-05-26 at 2 10 04 PM" src="https://user-images.githubusercontent.com/105234327/170476752-4a4f8e8b-d34a-4a08-83c9-5b23d949e85f.png">

values that can be 1, 2, 3 or 4 values where by each variant is valid in its own right i.e `margin: 1px` vs `margin: 1px 2px` vs `margin: 1px 2px 3px` vs `margin: 1px 2px 3px 4px` the expansion control would provide a interface for what would otherwise be manually admitted by keyboard.
</details>

## Known problems
- [ ] current bug with dropdown https://github.com/webstudio-is/webstudio-designer/issues/142

**Comment by kof** [comment]
In terms of implementation, I would split this relatively big UI into multiple composable once:

Primitives

1. masking should be a react hook that works with any host input component
2. horizontal drag interaction to change a numeric value should be a separate hook that works with any host input component
3. character position detection in an input field as a separate hook that gives you a callback with the currently hovered position relatively to text (e.g. input has: "text", you are hovering x, hook returns 2)
4. click on the chevron next to the unit opens up the Radix select component, but we need to decouple the chevron rendering+handler+select into a separate component that can be used together with a TextField. A bit of a concern here is that the click surface on chevron only is a too small surface for a good UX.
5. autocomplete data list should also be decoupled from Input so that one can compose the two

When I am composing the primitives into one component I should be able to have an input field that can have unit value with a select menu for the unit, at the same time you would be able to type a non-unit value.

__Use case 1__

Property "width" can have a numeric value with a unit, an "auto, min-content, max-content, fit-content".
Let's assume it has "auto" defined. 
- User can remove it and start typing a number. We automatically show the "px" unit selector. 
- User removes number - we hide "px" unit. 
- User clicks on the chevron next to px and selects a different unit. 
- At the edge of the input, we show a chevron for autocomplete, when the user clicks on it we show "auto, min-content, max-content, fit-content" as an autocomplete list
- User can press the arrow down or up to make autocomplete list open and ESC to close.
- When autocomplete list is open arrow up/down to navigate the items instead of closing/opening.

__Use case 2__

Gap value that has 2 values for row and column gap.

- each value can have unit with select box like above
- each value can have different units
- each value can have a horizontal drag interaction for changing the number
- masking prevents removing the delimiter character, but without disturbing the caret movement: e.g. if input has "10px |20px" and user removes the space with backspace - space is auto inserted but the caret goes the way user expects, so they end up at "10px| 20px" as if carent went through the space

**Comment by thysultan** [comment]
>User can press the arrow down or up to make autocomplete list open and ESC to close.

replaces the need for:

>At the edge of the input, we show a chevron for autocomplete, when the user clicks on it we show "auto, min-content, max-content, fit-content" as an autocomplete list

and also auto-complete opens when you focus/type in the field. It should be intuitive, having potentially two chevron's IMO doesn't feel like that. For example: in chrome dev-tools, there's no chevron to indicate/toggle auto-complete/suggestions, it's just there by default on focus/typing, the same is the case in other software interfaces like sublime, vscode, etc.

**Comment by kof** [comment]
@natlusyht actually just realized in case of autocomplete, you show it also when
1. user clicks on input
2. user starts typing

with this amount of redundancy there is no way they will miss the autocompletion, so we can skip the chevron, take this one as reference: https://mui.com/material-ui/react-autocomplete/#search-input

**Comment by kof** [comment]
![numeric-guesture-control](https://user-images.githubusercontent.com/52824/176518489-e7cdaa66-7c41-4d6b-8374-d368df1fa064.gif)

**Comment by kof** [comment]
@natlusyht when flex panel is merged, we can resume this one, right?

**Comment by kof** [comment]
- [ ] scrolling menu bug https://share.descript.com/view/sG6IPs5kxOU

**Comment by kof** [comment]
- [ ] row gap/column gap need to fit more numbers, currently onle number fully fits it, not even 2 digits! then in addition we have values like "normal" ... what can we do about it?

cc @taylornowotny 
<img width="104" alt="Screenshot 2022-09-10 at 11 37 46" src="https://user-images.githubusercontent.com/52824/189477807-b883c459-ae03-4b09-a9e1-2aedfea47d21.png">
<img width="222" alt="Screenshot 2022-09-10 at 11 38 25" src="https://user-images.githubusercontent.com/52824/189477808-55918f9a-ae86-4f12-b4b7-dce75e7594ff.png">

**Comment by kof** [comment]
- [ ] refactor all those nested selectors that reach into components to  CSS variables, like in this example implementation https://github.com/webstudio-is/webstudio-designer/pull/258

**Comment by taylornowotny** [comment]
> * [ ]  row gap/column gap need to fit more numbers, currently onle number fully fits it, not even 2 digits! then in addition we have values like "normal" ... what can we do about it?
> 
> 
> cc @taylornowotny <img alt="Screenshot 2022-09-10 at 11 37 46" width="104" src="https://user-images.githubusercontent.com/52824/189477807-b883c459-ae03-4b09-a9e1-2aedfea47d21.png"> <img alt="Screenshot 2022-09-10 at 11 38 25" width="222" src="https://user-images.githubusercontent.com/52824/189477808-55918f9a-ae86-4f12-b4b7-dce75e7594ff.png">

The issue here is parity with the design. The input fits 5 digits in figma, which should be plenty for defining a gap size. If we need more size then I would remove the icon and use a text label above the field instead. That's no problem but I don't think it's necessary.
<img width="666" alt="Screen Shot 2022-09-10 at 8 51 54 AM" src="https://user-images.githubusercontent.com/86495896/189491297-abe8a3dd-d18d-4fae-8c8c-44e0ec4fbf18.png">

Are you sure we need space for "Normal"? According to MDN normal is just the initial value. We can represent that with a blank field. Normal = no gap = no value in the field.

https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap
