### ISSUE TITLE
Don't set a value if it hasn't changed

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#644]
Currently you can get a "set" value if you just focus and then blur the value or if you delete and type the exact same value as there was before by default or from a preset

**Comment by istarkov** [comment]
We need to publish anyway, to reset `css` variable used during "preview".
So we can't stop it on control level (how to reset css var?)

And the only places we can avoid additional setStates are here 
https://github.com/webstudio-is/webstudio-designer/blob/f64694397ea82dc40237f7000555d17ad7587d5f/apps/designer/app/designer/features/style-panel/shared/use-style-data.ts#L135

And instead of calling `updateStyle` we can call `update.operation === "delete"` for css variable
and
