### ISSUE TITLE
Move content-editable toolbar to workspace-tools and replace content editor with lexical.dev

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#68]
Currently the toolbar is still inside the canvas/iframe and now we moved outlines into workspace tools and they get rendered on top of the text editing toolbar

![image](https://user-images.githubusercontent.com/52824/173866199-82f9908f-dcda-4915-9b42-0f457e0db297.png)

**Comment by okonet** [comment]
I'm thinking that in order to avoid all possible and uncovered edge cases like https://github.com/webstudio-is/webstudio-designer/issues/77 we should not rely on content-editable at all. Instead, we could build a UI in the designer using the outline layer (since #56 is merged) and use props to pass down the children to components. 

Additionally, I think it would be great to show `children` prop explicitly somehow in the advanced tab. This would solve two potential use cases: users can edit content in the side panel (consistently with styles), and it would allow editing non-children props like `value` in the `<input type="button">`.

WDYT?

**Comment by okonet** [comment]
You can take a look at https://docs.slatejs.org since its a similar abstraction like https://lexical.dev. But from my past experience https://prosemirror.net worked the best.

**Comment by kof** [comment]
Follow up issue https://github.com/webstudio-is/webstudio-designer/issues/107
