### ISSUE TITLE
Image optimizations

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#70]
Lets do some research for image optimization service we could use out of the box that would allow us to load any image type over that service from our S3 storage and it would take care of all optimizations, resizing, responsive sizes and serving over a CDN.

Lets find the best service that has also a reasonable price.

**Comment by andrasbacsai** [comment]
Then I would go with Cloudflare Images. It has everything we need.

**Comment by andrasbacsai** [comment]
We need to think about how we should implement this, as we have the asset worker/bucket implementation for images.

If we use Cloudflare Images, we do not need the bucket implementation, because Cloudflare Images have it's own storage (probably a bucket 😀). We could reuse the current worker to:

- Upload to Cloudflare Images (instead of bucket).
- Retrieve any image (with any variant) through the worker (instead of a bucket).

Wdyt?

**Comment by andrasbacsai** [comment]
Yes, it is done for now.
