### ISSUE TITLE
Assets handling in a cloned project

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#872]
- [x] Show assets in the cloned project (currently we don't show them)
- [x] Ensure deleting an asset in the original project doesn't delete it from the cloned one
- [x]  Ensure deleting an asset in the cloned project doesn't delete it in the original one

**Comment by rpominov** [comment]
Going to solve it like this:

1. When project is cloned, clone assets along with `id`. So `asset.id` will not be unique, but `asset.id+asset.projectId` will remain unique
2. Since we kept `asset.id` when it's referenced from props or styles, the reference will still work
3. When deleting an asset, will delete file from storage only if there are no assets in other projects that use the same file

@kof @istarkov does this sound good?

**Comment by istarkov** [comment]
We already have that asset id is not unique and uniq key is `@@id([id, projectId])`
projectId seems like already added to most/all queries, as it must be done for authorization reasons too

**Comment by rpominov** [comment]
> @rpominov so basically to prevent the need to update trees/props with the new asset id:
> 
> 1. we keep the asset id
> 2. we make asset id non-unique
> 3. we add project id to all queries that update or read assets to have assetId + projected as a unique selector
> 
> correct?

Yes, and as @istarkov said number 3 is probably already the case, but I will double-check
